server:
  port: 8000
spring:
  application:
    name: mydemo
    version: 1.0
    copyrightYear: 2019
    demoEnabled: true
    addressEnabled: true
    profile: D:/wy/wydemo/wyproject
  profiles:
    active: dev
  messages:
      # 国际化资源文件路径
    basename: static/i18n/messages
#数据库设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 10
      min-idle: 10
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 20000
      filters: wall,stat
  thymeleaf:
#    prefix: /templates/views/
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8

#分页配置
pagehelper: 
  autoDialect: true
  closeConn: false
  reasonable: true

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false



# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 10

xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*