#数据库配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydemo?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: wy940830...


spring:
  datasource:
    url: jdbc:mysql://47.110.132.202:3306/mydemo?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: wyDB
    password: wy940830...